### ISSUE TITLE
command 'break' doesn't work

### ISSUE THREAD

**Issue by Himmelt** [Himmelt/Essentials#1]
```java
[21:53:49 ERROR]: 命令 break 失败:
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/Set;I)Lorg/bukkit/block/Block;
        at com.earth2me.essentials.commands.Commandbreak.run(Commandbreak.java:22) ~[Essentials.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:149) ~[Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:435) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:339) [Essentials.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.1.0.1]
```

**Comment by Himmelt** [comment]
`org.bukkit.entity.Player.getTargetBlock(Ljava/util/Set;I)Lorg/bukkit/block/Block;`
这个方法只有1.8及以后才有

**Comment by Himmelt** [comment]
Quorra 中已添加对应方法
